[project]
name = "sgtfunc"
version = "0.0.0+local"
dependencies = [
    "muxtools>=0.0.9",
    "vsdenoise>=2.5.1",
    "vskernels>=3.0.2",
    "vsmasktools>=1.2.1",
    "vsrgtools>=1.6.2",
    "vsscale>=2.0.1",
    "vstools>=3.0.1"
]
