[project]
name = "encodes"
requires-python = ">=3.11"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "3.11.5"
vapoursynth = {version = "65", optional = true}

# pypi
pymediainfo = "6.1.0"
sox = "1.5.0"

# JET
lvsfunc = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/lvsfunc", rev = "dd21e138d0f03bf0667a9831844a5efe790cbbac"}
muxtools = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/muxtools", rev = "5bc0986e26a3793cc6c73134131b74534dd99a30"}
vsaa = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-aa", rev = "2c068f02026780df290d62722b944d64b61eb18c"}
vsdeband = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-deband", rev = "d1a3eac0389157792c21511cab4e480552f3a671"}
vsdehalo = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-dehalo", rev = "4788fa57b25cbd216b879e1b308ad8696ab2035b"}
vsdenoise = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise", rev = "2068f6583fedbef2cf53577dc265ee38d8845d94"}
vsexprtools = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-exprtools", rev = "ce28ecf44e2525ada73725b47e4f7c81aada12b9"}
vskernels = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-kernels", rev = "73419b2399ce8e1d652bbf07d543245214d9d621"}
vsmasktools = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-masktools", rev = "e80bffbf0087e8c9edb75fd056179520a7ded877"}
vsmuxtools = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-muxtools", rev = "c477abf96beca0b64a26f2e7826473e5611f7e44"}
vspreview = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview", rev = "bb68df880a1b6e0f4ba4163e92eb397304c53f1b"}
vsrgtools = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-rgtools", rev = "a9a5fd235df86f097c4669dea89de14c3a0d613f"}
vsscale = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-scale", rev = "69d0085f730f3580950f3e0f24b8a18da3d9e5b8"}
vssource = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-source", rev = "ebad21823a416b94437cce00434287eeb3337630"}
vstools = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools", rev = "67d83409a326f202b6bf36393c6e35e8a46de3db"}

# misc
awsmfunc = {git = "https://github.com/OpusGang/awsmfunc", rev = "77c01e914be5ba37fb2e08bf53e47f73649cffdf"}
jvsfunc = {git = "https://github.com/dnjulek/jvsfunc", rev = "0200b4fe464557fb62ea1abdc04e6851b683bf2e"}
stgpytools = {git = "https://github.com/Setsugennoao/stgpytools", rev = "a57a6fa28dc08d52268814b81f80e3814eb060b6"}
vodesfunc = {git = "https://github.com/Vodes/vodesfunc", rev = "cea015749a39e6e259ddd64b4e76c0684ce1ee35"}
vs-rekt = {git = "https://github.com/OpusGang/rekt", rev = "37df56203c7d39c0aa5a9bcb15251dc06a7704ee"}

# For muxtools patch to sanitize font names.
pathvalidate = "3.2.0"

# local
sgtfunc = {path = "src/sgtfunc", develop = true}

[tool.poetry.group.dev.dependencies]
mypy = "1.9.0"
ruff = "0.4.1"

fontvalidator = {git = "https://github.com/Funami580/Myaamori-Aegisub-Scripts", branch = "fix_mkv_mimetype_comparison", rev = "98f629a23837d3fb8de1aeddea3541d8d13be614", subdirectory = "scripts/fontvalidator"}
getfscaler = {git = "https://github.com/Jaded-Encoding-Thaumaturgy/getfscaler", rev = "7cd966d8ed7dae7a7134be9e55190c71ed0de9dd"}
getnative = {git = "https://github.com/Infiziert90/getnative", rev = "720c3953d7668d0d5daf8abf827d63b3936d6d2b"}
getnativef = {git = "https://github.com/Vodes/getnativef", rev = "7038fed0737287f2bd32580ef549f6facb4932bf"}

# dependencies of vspreview plugins
scipy = "1.13.0"

[tool.mypy]
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
check_untyped_defs = true

disallow_any_generics = true
disallow_subclassing_any = true
warn_return_any = true

warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
warn_unreachable = true
show_error_codes = true

no_implicit_optional = true

show_error_context = false
show_column_numbers = true
color_output = true
error_summary = true
pretty = true

[tool.ruff]
line-length = 120
src = ["src"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN101",  # Missing type annotation for `self` in method (deprecated)
    "C901",    # `x` is too complex
    "COM812",  # Trailing comma missing
    "D",       # pydocstyle
    "E501",    # Line too long
    "EM",      # flake8-errmsg
    "ERA001",  # Found commented-out code
    "INP001",  # File `x` is part of an implicit namespace package. Add an `__init__.py`.
    "ISC001",  # Implicitly concatenated string literals on one line
    "PLR0913", # Too many arguments in function definition
    "PLR2004", # Magic value used in comparison
    "S101",    # Use of `assert` detected
    "S311",    # Standard pseudo-random generators are not suitable for cryptographic purposes
    "T201",    # `print` found
    "TCH003",  # Move standard library import `...` into a type-checking block
    "TD002",   # Missing author in TODO.
    "TD003",   # Missing issue link on the line following this TODO.
    "TRY003",  # Avoid specifying long messages outside the exception class
]

[tool.ruff.lint.isort]
known-first-party = ["sgtfunc"]

[tool.ruff.lint.per-file-ignores]
"src/MysteriaFriends/*.py" = ["FBT003"]
"src/WhisperedWords/*.py" = ["FBT003"]
"__init__.py" = ["F401"]
