name: CI
on: [pull_request, push]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - uses: actions/checkout@v4.1.5
      - run: ${{ env.CC }} --version
      - name: Update pip
        run: |
          pip install --upgrade --user pip
          pip --version
      - name: Update pipx
        run: |
          pip install --upgrade --user pipx
          pipx --version
      - name: Install poetry
        run: |
          pipx install poetry
          poetry --version
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.12.3'
          cache: poetry
          cache-dependency-path: poetry.lock
      - name: Install VapourSynth
        uses: rlaphoenix/install-vapoursynth-action@v2.1.1
        with:
          version: 68
          cache: true
      - run: pip inspect
      - name: Verify VapourSynth install
        run: python3 -c "import vapoursynth; print(vapoursynth.core)"
      - name: Check lockfile
        run: poetry check --lock
      - name: Install dependencies
        run: poetry install
      - name: mypy
        run: for dir in src/*/; do poetry run mypy --ignore-missing-imports "$dir"; done
        continue-on-error: true
      - name: ruff
        run: poetry run ruff check --output-format=github .
        continue-on-error: true
