name: CI
on: [pull_request, push]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - uses: actions/checkout@v4.1.0
      - run: ${{ env.CC }} --version
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.11.5'
          cache: 'pip'
      - name: Update pip
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip --version
      - name: Install VapourSynth build dependencies
        run: python3 -m pip install --upgrade cython==0.29.35 setuptools wheel
      - name: Install VapourSynth
        uses: rlaphoenix/install-vapoursynth-action@v2.0.2
        with:
          version: 63
          cache: true
      - run: python3 -m pip inspect
      - name: Verify VapourSynth install
        run: python3 -c "import vapoursynth; print(vapoursynth.core.version())"
      - name: Setup venv
        run: python3 -m venv --clear --system-site-packages .venv
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          python3 -m pip install -r requirements.txt -r requirements-dev.txt
      - name: Install sgtfunc
        run: |
          source .venv/bin/activate
          python3 -m pip install -e src/sgtfunc/
      - name: mypy
        run: |
          source .venv/bin/activate
          for dir in src; do python3 -m mypy --ignore-missing-imports "$dir"; done
        continue-on-error: true
      - name: flake8
        run: |
          source .venv/bin/activate
          python3 -m flake8
        continue-on-error: true
      - name: black
        run: |
          source .venv/bin/activate
          python3 -m black --check --diff .
        continue-on-error: true
      - name: isort
        run: |
          source .venv/bin/activate
          python3 -m isort --check --diff .
        continue-on-error: true
